apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld-springboot
  namespace: helloworld
spec:
  secretName: helloworld-springboot

  duration: 1h
  renewBefore: 10m
  subject:
    organizations:
      - Gimi
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: example.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    # - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - localhost
  # ipAddresses:
  #   - 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
