#!/usr/bin/env bash

openssl pkcs12 \
  -export \
  -in /mnt/certs/tls.crt \
  -inkey /mnt/certs/tls.key \
  -certfile /mnt/certs/tls.crt \
  -password "pass:${KEYSTORE_PASS}" \
  -out /mnt/keystore/keystore.p12
